
export const GET_PENDING_VENDORS_REQUEST = 'GET_PENDING_VENDORS_REQUEST';
export const GET_PENDING_VENDORS_SUCCESS = 'GET_PENDING_VENDORS_SUCCESS';
export const GET_PENDING_VENDORS_FAILURE = 'GET_PENDING_VENDORS_FAILURE';

export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAILURE = 'GET_ALL_PRODUCTS_FAILURE';